name: Python application workflow

on:
  push:
    branches:
      - main  # يبدأ العمل عند الدفع إلى فرع "main"
  pull_request:
    branches:
      - main  # يبدأ العمل عند إنشاء طلب سحب إلى فرع "main"

jobs:
  test:
    runs-on: ubuntu-latest  # تشغيل على نظام Ubuntu

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # إصدارات Python المدعومة

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # تحميل الكود المصدري من المستودع

    - name: Set up Python
      uses: actions/setup-python@v2  # إعداد إصدار Python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # تحديث pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt file found."; fi

    - name: Run tests
      run: |
        pytest  # تشغيل الاختبارات باستخدام pytest
